spring.application.name=lab10
spring.datasource.url=jdbc:mysql://localhost:3306/bd_lab10?createDatabaseIfNotExist=true
server.port=3244
spring.datasource.username=andreea
spring.datasource.password=Andreea?
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
