spring.application.name=lab11
spring.datasource.url=jdbc:mysql://localhost:3306/bd_lab11?createDatabaseIfNotExist=true
server.port=3244
spring.datasource.username=andreea
spring.datasource.password=Andreea?
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never